In [1]:
my_list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
np.eye(4)
#identity matrix generat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.79098343, 0.29032702, 0.73119355, 0.74963673, 0.46041353])

In [21]:
np.random.rand(5,4)

array([[0.31839302, 0.26304739, 0.87719247, 0.28878399],
       [0.38171324, 0.39722928, 0.84917049, 0.29206597],
       [0.1194472 , 0.12619238, 0.96894018, 0.2731291 ],
       [0.40239543, 0.43090221, 0.50141974, 0.99684629],
       [0.03683298, 0.953687  , 0.35533219, 0.14740215]])

In [22]:
np.random.randn(2)

array([-1.80238651,  0.25014278])

In [23]:
np.random.randn(4,5)

array([[ 1.16574202, -0.88796214, -1.72037541,  1.05368571, -0.3455301 ],
       [ 0.68781306,  1.2938164 , -0.95431595, -1.37346908,  1.00716047],
       [-0.09758487, -1.33793568, -0.11775928,  0.23611608, -1.30923515],
       [ 1.6333193 , -0.92592676,  1.02134385, -0.02611302,  0.10327201]])

In [36]:
np.random.randint(1,100, 10)

array([76, 65, 50,  1, 25, 30,  8, 35, 25, 90])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([38, 11,  6,  5, 46, 21, 18, 30, 25, 41])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([38, 11,  6,  5, 46, 21, 18, 30, 25, 41])

In [44]:
ranarr.max()

46

In [45]:
ranarr.min()

5

In [47]:
ranarr.argmax()

4

In [48]:
ranarr.argmin()

3

In [49]:
arr.shape

(25,)

In [52]:
arr = arr.reshape(5,5)

In [53]:
arr.shape

(5, 5)

In [54]:
arr.shape

(5, 5)

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[3]

3

In [58]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr[0:5]

array([0, 1, 2, 3, 4])